<?php

namespace Database\Seeders;

use App\Models\StatCost;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class StatCostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $statCosts = [
            // Raza 1
            [
                'race_id' => 1,
                'stat_type_id' => 1,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 2,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 3,
                'start' => 0,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 3,
                'start' => 50,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 3,
                'start' => 150,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 3,
                'start' => 250,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 4,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 4,
                'start' => 100,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 4,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 4,
                'start' => 300,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 4,
                'start' => 400,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 5,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 5,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 5,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 5,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 5,
                'start' => 80,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 6,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 6,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 6,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 6,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 1,
                'stat_type_id' => 6,
                'start' => 80,
                'cost_per_point' => 5,
            ],

            // Raza 2
            [
                'race_id' => 2,
                'stat_type_id' => 1,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 2,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 3,
                'start' => 0,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 3,
                'start' => 50,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 3,
                'start' => 150,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 3,
                'start' => 250,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 4,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 4,
                'start' => 100,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 4,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 4,
                'start' => 300,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 4,
                'start' => 400,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 5,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 5,
                'start' => 100,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 5,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 5,
                'start' => 300,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 5,
                'start' => 400,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 6,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 6,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 6,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 6,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 2,
                'stat_type_id' => 6,
                'start' => 80,
                'cost_per_point' => 5,
            ],

            // Raza 3
            [
                'race_id' => 3,
                'stat_type_id' => 1,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 2,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 3,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 3,
                'start' => 50,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 3,
                'start' => 150,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 3,
                'start' => 250,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 3,
                'start' => 350,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 4,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 4,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 4,
                'start' => 60,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 4,
                'start' => 100,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 4,
                'start' => 140,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 5,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 5,
                'start' => 100,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 5,
                'start' => 150,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 5,
                'start' => 230,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 5,
                'start' => 330,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 6,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 6,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 6,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 6,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 3,
                'stat_type_id' => 6,
                'start' => 80,
                'cost_per_point' => 5,
            ],

            // Raza 4
            [
                'race_id' => 4,
                'stat_type_id' => 1,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 2,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 3,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 3,
                'start' => 100,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 3,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 3,
                'start' => 300,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 3,
                'start' => 400,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 4,
                'start' => 0,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 4,
                'start' => 50,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 4,
                'start' => 150,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 4,
                'start' => 250,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 5,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 5,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 5,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 5,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 5,
                'start' => 80,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 6,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 6,
                'start' => 100,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 6,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 6,
                'start' => 300,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 4,
                'stat_type_id' => 6,
                'start' => 400,
                'cost_per_point' => 5,
            ],

            // Raza 5
            [
                'race_id' => 5,
                'stat_type_id' => 1,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 2,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 3,
                'start' => 0,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 3,
                'start' => 50,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 3,
                'start' => 150,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 3,
                'start' => 250,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 4,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 4,
                'start' => 100,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 4,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 4,
                'start' => 300,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 4,
                'start' => 400,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 5,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 5,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 5,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 5,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 5,
                'start' => 80,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 6,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 6,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 6,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 6,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 5,
                'stat_type_id' => 6,
                'start' => 80,
                'cost_per_point' => 5,
            ],

            // Raza 6
            [
                'race_id' => 6,
                'stat_type_id' => 1,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 2,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 3,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 3,
                'start' => 100,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 3,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 3,
                'start' => 300,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 3,
                'start' => 400,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 4,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 4,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 4,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 4,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 4,
                'start' => 80,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 5,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 5,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 5,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 5,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 5,
                'start' => 80,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 6,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 6,
                'start' => 50,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 6,
                'start' => 100,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 6,
                'start' => 150,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 6,
                'stat_type_id' => 6,
                'start' => 200,
                'cost_per_point' => 5,
            ],

            // Raza 7
            [
                'race_id' => 7,
                'stat_type_id' => 1,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 2,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 3,
                'start' => 0,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 3,
                'start' => 50,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 3,
                'start' => 150,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 3,
                'start' => 250,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 4,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 4,
                'start' => 100,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 4,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 4,
                'start' => 300,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 4,
                'start' => 400,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 5,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 5,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 5,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 5,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 5,
                'start' => 80,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 6,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 6,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 6,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 6,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 7,
                'stat_type_id' => 6,
                'start' => 80,
                'cost_per_point' => 5,
            ],

            // Raza 8
            [
                'race_id' => 8,
                'stat_type_id' => 1,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 2,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 3,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 3,
                'start' => 100,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 3,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 3,
                'start' => 300,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 3,
                'start' => 400,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 4,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 4,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 4,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 4,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 4,
                'start' => 80,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 5,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 5,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 5,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 5,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 5,
                'start' => 80,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 6,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 6,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 6,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 6,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 8,
                'stat_type_id' => 6,
                'start' => 80,
                'cost_per_point' => 5,
            ],

            // Raza 9
            [
                'race_id' => 9,
                'stat_type_id' => 1,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 2,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 3,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 3,
                'start' => 50,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 3,
                'start' => 150,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 3,
                'start' => 250,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 3,
                'start' => 350,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 4,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 4,
                'start' => 50,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 4,
                'start' => 150,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 4,
                'start' => 250,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 4,
                'start' => 350,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 5,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 5,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 5,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 5,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 5,
                'start' => 80,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 6,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 6,
                'start' => 50,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 6,
                'start' => 100,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 6,
                'start' => 150,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 9,
                'stat_type_id' => 6,
                'start' => 200,
                'cost_per_point' => 5,
            ],

            // Raza 10
            [
                'race_id' => 10,
                'stat_type_id' => 1,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 2,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 3,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 3,
                'start' => 50,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 3,
                'start' => 250,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 3,
                'start' => 300,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 3,
                'start' => 400,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 4,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 4,
                'start' => 100,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 4,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 4,
                'start' => 300,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 4,
                'start' => 400,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 5,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 5,
                'start' => 100,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 5,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 5,
                'start' => 300,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 5,
                'start' => 400,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 6,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 6,
                'start' => 20,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 6,
                'start' => 40,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 6,
                'start' => 60,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 10,
                'stat_type_id' => 6,
                'start' => 80,
                'cost_per_point' => 5,
            ],

            // Raza 11
            [
                'race_id' => 11,
                'stat_type_id' => 1,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 2,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 3,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 3,
                'start' => 100,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 3,
                'start' => 150,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 4,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 4,
                'start' => 100,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 4,
                'start' => 150,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 5,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 5,
                'start' => 100,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 5,
                'start' => 150,
                'cost_per_point' => 5,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 6,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 6,
                'start' => 100,
                'cost_per_point' => 4,
            ],
            [
                'race_id' => 11,
                'stat_type_id' => 6,
                'start' => 150,
                'cost_per_point' => 5,
            ],

            // Raza 12
            [
                'race_id' => 12,
                'stat_type_id' => 1,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 2,
                'start' => 0,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 3,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 3,
                'start' => 50,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 3,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 4,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 4,
                'start' => 50,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 4,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 5,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 5,
                'start' => 50,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 5,
                'start' => 200,
                'cost_per_point' => 3,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 6,
                'start' => 0,
                'cost_per_point' => 1,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 6,
                'start' => 50,
                'cost_per_point' => 2,
            ],
            [
                'race_id' => 12,
                'stat_type_id' => 6,
                'start' => 200,
                'cost_per_point' => 3,
            ],
        ];

        foreach ($statCosts as $statCost) {
            StatCost::updateOrCreate(['id' => $statCost['id']], $statCost);
        }
    }
}
